### ISSUE TITLE
[Polymer 1.0] fluid not working 

### ISSUE THREAD

**Issue by 19Gerhard85** [GoogleWebComponents/google-youtube#40]
Hey guys,

I tried to include a YouTube video into my site, unfortunately the fluid parameter isnt working.

```html
<paper-material elevation="1">
    <google-youtube
        video-id="qyJ9xctOMCI"
        fluid="true"
        rel="0"
        start="0"
        autoplay="0">
    </google-youtube>
</paper-material>
```

The width of the embedded player is 100% but the height is only 150px small instead of a 16:9 ratio.

**Comment by LaserLock** [comment]
:+1:

**Comment by 19Gerhard85** [comment]
@jeffposnick Any hints?

**Comment by jeffposnick** [comment]
Does it behave as expected when you use `fluid` instead of `fluid="true"`? Boolean attributes work based on their presence/absence, and you're not supposed to assign a value to them.

**Comment by 19Gerhard85** [comment]
Thanks for your reply Jeff.

Nope <code>fluid</code> doesn't work neither.

If I try to debug it, add at a <code>console.log(this.width);</code> to line 408 in google-youtube.html I get a width of 480px. This couldn't be correct.

![google-youtube](https://cloud.githubusercontent.com/assets/1492978/8425042/1dadf848-1f02-11e5-885f-b4f78e470add.png)

**Comment by rafalee** [comment]
Having the same issue here, anyone figured out a work around?
