### ISSUE TITLE
Component keeps playing after a user navigates to a new SPA page.

### ISSUE THREAD

**Issue by gedw99** [GoogleWebComponents/google-youtube#44]
I am using this polymer component on a large SPA. 
The problem occurs when the user navigates to another page, and the video keeps playing in the background of course, since its an SPA (like many polymer sites).

The core problem is that the component is not routing away. This is not a bug, but is a common best practice designer problem.

Steps to reproduce:
1. Place component on any page in an iron-pages element
2. In the browser, navigate to a different page. The video will keep playing.

Ideas how to resolve:
- If this component can detect that its page parent is no longer the one that the router is on, it can automatically stop. This is a good solution, because its emergent, and just works.
- At the Iron-Page, sense that the user has selected to navigate away, and tell the component to stop playing.
- Any other ideas welcome !!!!

**Comment by ebidel** [comment]
I don't see a way to bake this into the component. There's no way for the element to know what context it's in or even know if it's "hidden". 

I suggest calling `pause()` when you navigate to a new route. That's what we did on the Polymer Summit site: 
https://github.com/Polymer/docs/blob/f1288bbdf68da3d0fb00676ee74c50a408ea1117/summit/app/src/routing.html#L25

**Comment by gedw99** [comment]
Thanks. Appreciated. Will give it a shot
