### ISSUE TITLE
Using src instead of ID?

### ISSUE THREAD

**Issue by caraya** [GoogleWebComponents/google-youtube#45]
I'm working with a third party API that provides a URL to a Youtube video. Is is possible to use that (url) instead of a video ID  with this element?

If not possible, is there an easy way to just extract the video ID from a URL?

**Comment by ebidel** [comment]
You can extract the video id fairly easily with a computed property. Something like: https://github.com/GoogleChrome/ioweb2015/blob/e33352f89034e77f54afdb1fc685439f3962803a/app/scripts/helper/elements.js#L395.
