### ISSUE TITLE
Adding padding-top for fluid attribute on #container instead of host element

### ISSUE THREAD

**Issue by n4gashi** [GoogleWebComponents/google-youtube#50]
There seem to be an issue when using fluid attribute into an `iron-flex-layout` that prevents the viewport of the video to be responsive.

Instead of `padding-top` on the host element, should be better to add it to the first children (`div#container`) to fit any kind of layout.

Will probably submit a PR.

Screenshot1 : initial padding top on `:host` element
Screenshot2 : padding top used on `#container` instead

![screen shot 2015-11-30 at 2 44 32 pm](https://cloud.githubusercontent.com/assets/10873860/11487118/f380db6a-9771-11e5-8f54-b6b9541ae6e5.png)
![screen shot 2015-11-30 at 2 51 53 pm](https://cloud.githubusercontent.com/assets/10873860/11487119/f38189d4-9771-11e5-84b6-1f831a80873d.png)

**Comment by n4gashi** [comment]
PR sent at https://github.com/GoogleWebComponents/google-youtube/pull/51

**Comment by robdodson** [comment]
@n4gashi can you tell me what markup (html/css) you were using to produce the first screenshot? I'd just like to see what caused the error state.

**Comment by n4gashi** [comment]
@robdodson the HTML markup didn't changed between two screens. The css that changed is what I've added to the PR.

Just to let you know about the HTML structure, here is it : 

```
<dom-module id="recording-container">
  <template>
    <link rel="stylesheet" href="../static/css/elements/recording-container.css">

    <!-- CONTENT (VIDEO) -->
    <div id="recording-video">
      <!-- VIDEO_NATIVE -->
      <template is="dom-if" if="{{ isVideoNative }}">
        // Layout if isVideoNative is true
      </template>

      <!-- VIDEO -->
      <template is="dom-if" if="{{ isVideoYoutube }}">
        <style>
          /* TODO : remove this as PR on google-youtube component has been merged */
          google-youtube{ padding-top: 0 !important; height:500px; }
        </style>
        <google-youtube
          video-id="{{ youtubeId }}"
          rel="0"
          fluid
          autoplay="true">
        </google-youtube>
      </template>

      <!-- AUDIO -->
      <template is="dom-if" if="{{ isAudio }}">
        // Layout if isAudio is true
      </template>
    </div>
  </template>
  <script>
  // Polymer init
  ...
  </script>
</dom-module>
```

Basically, the result shown in the first screen is what I got when putting `fluid` to the `<google-youtube>` element.

I was wondering at first sight that it was due to `iron-flex-layout` cause the container had initially `layout horizontal`, but now I am not using it anymore, I think this is maybe due to the fact I'm using `google-youtube` into another polymer component.

What do you think about ?
I'm relatively new to Polymer, so maybe I missed something. The sure thing is that the padding wasn't added to the right element though.

**Comment by robdodson** [comment]
hm i'm not able to reproduce this just tossing the element into another custom element (http://jsbin.com/fubari/1/edit?html,output)

Not saying that there isn't a bug, but I'd like to create a reproducible test case before adding the patch. Do you think you could recreate your layout using that jsbin in order to highlight the issue?
