### ISSUE TITLE
Remove default video

### ISSUE THREAD

**Issue by BLamy** [GoogleWebComponents/google-youtube#54]
`https://github.com/GoogleWebComponents/google-youtube/blob/master/google-youtube.html#L131`

There seems to be a default video set for google-youtube. I'd rather have the youtube error message than a random video in the event of an error.

Also seems to override the video I'm trying to play on about ever 3rd load.

**Comment by ebidel** [comment]
+1 would you like to submit a PR?

**Comment by BLamy** [comment]
https://github.com/GoogleWebComponents/google-youtube/pull/55

**Comment by jeffposnick** [comment]
The underlying YouTube `<iframe>` embed, at least as of the last time I checked, will get into an unrecoverable state if you try to initialize it without a video. That's what motivated providing an actual video id as a fallback, since you can at least recover from that if for some reason it falls back to it.

Rather than go ahead with #55, I would be more interested in seeing a reproduction of how the default overrides your video id. Can you point us to the code?

**Comment by BLamy** [comment]
http://jsbin.com/modevabaho/1/edit?html,console,output

Is a simple element which calls out to the youtube API. Downloads a playlist and then tries to set the videoId google-youtube. 

You can see almost every time the page loads the default video comes up instead of the one I set. If you inspect the `videoId` on the google-youtube element you will see the id for the first video from the AJAX response. However, that is not the video that is playing.

**Comment by jeffposnick** [comment]
You should wait to stamp out the `<google-youtube>` element until you have your initial video id, by wrapping it in a `<template is="dom-if">`. Here's an example:

http://jsbin.com/xigaxo/edit?html,output

**Comment by BLamy** [comment]
You don't see that as a problem?

**Comment by jeffposnick** [comment]
If you've got a variable that's set asynchronously, then as a general rule, you'll want to delay using it until you're sure it's set. Wrapping things in a `<template is="dom-if">` is a fairly common pattern (at least in my experience), but I could see how it would be non-obvious.

Let me make sure that there aren't any unintended consequences to moving that logic into the core `<google-youtube>` element. If it looks like it could be done cleanly, it sounds like a worthwhile addition.
