### ISSUE TITLE
wmode=opaque by default

### ISSUE THREAD

**Issue by BLamy** [GoogleWebComponents/google-youtube#60]
This web component should probably set `wmode` by default so that IE won't place videos above everything. 

The way this element is now; If I place a `google-youtube` inside of a `paper-scroll-header-panel` the video will go over the `paper-toolbar` when scrolling on IE (Edge, and lower) which probably isn't desired behavior for most.

**Comment by ebidel** [comment]
@jeffposnick ?

**Comment by jeffposnick** [comment]
Just to clarify, `<google-youtube wmode="opaque">` element accomplishes what you'd expect, correct?

In general, my philosophy with `<google-youtube>` has been to use the defaults of the underlying `<iframe>` embed.

Given the decreased relevance of Flash playback (though it's obviously still used for some browser/video combinations) and the fact there might be developers who, intentionally or not, depend on the existing default `wmode` setting, I'm inclined to leave the default as is.

**Comment by BLamy** [comment]
@jeffposnick That's exactly correct, `<google-youtube wmode="opaque">` works as intended. Took me a little googling to arrive at that solution.

It's kind of a cross browser gotcha.

**Comment by jeffposnick** [comment]
Given that the official `<iframe>` embedded YouTube player defaults to leaving it unset, I think that having `<google-youtube>` do the same thing would keep things consistent.

I'm sorry that the solution wasn't obvious, but it sounds like you do have a workaround now for your use case.
